version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: velib_dw
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: change_me
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  # api:
  #   build: ./api
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db

volumes:
  pgdata:
